### ISSUE TITLE
pixel ratio ignored

### ISSUE THREAD

**Issue by myevi** [swensson/jarvis-chart#1]
hello guys! 
why you didn`t use pixel ratio? blur on retina2k
https://github.com/swensson/jarvis-chart/blob/master/src/jarvis-chart/plugins/renders/Canvas/context.js -> fix here

**Comment by lxchurbakov** [comment]
Ублюдок, мать твою, а ну иди сюда, говно собачье, решил ко мне лезть? Ты, засранец вонючий, мать твою, а? Ну иди сюда, попробуй меня трахнуть, я тебя сам трахну, ублюдок, онанист чертов, будь ты проклят, иди идиот, трахать тебя и всю семью, говно собачье, жлоб вонючий, дерьмо, сука, падла, иди сюда, мерзавец, негодяй, гад, иди сюда, ты — говно, жопа!

**Comment by myevi** [comment]
molodci gays, rabotaete v pravil`nom direction! tak derzhat`
